font_family      Terminess Nerd Font
font_size        13
window_padding_width 14

# Ventana y Bordes
window_padding_width 10
adjust_line_height  110%

# Paleta Monocromática Oscura (Zero Mono Dark)
foreground            #ffffff
background            #000000
selection_foreground  #000000
selection_background  #ffffff

# Colores de la terminal (Invertidos)
color0  #ffffff
color8  #aaaaaa
color1  #ffffff
color9  #aaaaaa
color2  #ffffff
color10 #aaaaaa
color3  #ffffff
color11 #aaaaaa
color4  #ffffff
color12 #aaaaaa
color5  #ffffff
color13 #aaaaaa
color6  #ffffff
color14 #aaaaaa
color7  #555555
color15 #000000

# Desactivar campana
enable_audio_bell no
